/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.MessageFormat;

public class App {
    public static void main(String[] args) throws Exception {
        String serviceKey = "xGMSjzWMa5MtIyn%2FRgVvPV1MV9%2BNVznfh3uBp%2FBB1iEUqT7ewoagM3mbTVzxXl0RPNrnfAGkDdjrJYc39VqhpA%3D%3D";
        int pageNo = 1;
        int numOfRows = 5;
        String urlPattern = "http://openapi.kised.or.kr/openapi/service/rest/ContentsService/getAnnouncementList?serviceKey={0}&pageNo={1}&numOfRows={2}";
        String httpsURL = MessageFormat.format(urlPattern, new Object[]{ serviceKey, pageNo, numOfRows });
        URL myUrl = new URL(httpsURL);
        HttpURLConnection conn = (HttpURLConnection)myUrl.openConnection();

        System.out.println("RESPONSE CODE : " + conn.getResponseCode());
        System.out.println("RESPONSE MESSAGE : " + conn.getResponseMessage());

        InputStream is = conn.getInputStream();
        InputStreamReader isr = new InputStreamReader(is);
        BufferedReader br = new BufferedReader(isr);

        String inputLine;
        System.out.println("http request read");
        while ((inputLine = br.readLine()) != null) {
            System.out.println(inputLine);
        }
    }
}
